resource "google_organization_iam_custom_role" "ternary_service_agent" {
  role_id     = "TernaryCMPServiceAgent"
  org_id      = data.google_organization.org.org_id # or the org number in quotes "123456789"
  title       = "Ternary CMP Service Agent"
  description = "Permissions for Ternary to access your cloud for cost insights"
  permissions = [
    "bigquery.bireservations.get",
    "bigquery.capacityCommitments.get",
    "bigquery.capacityCommitments.list",
    "bigquery.jobs.get",
    "bigquery.jobs.list",
    "bigquery.jobs.listAll",
    "bigquery.reservationAssignments.list",
    "bigquery.reservationAssignments.search",
    "bigquery.reservations.get",
    "bigquery.reservations.list",
    "cloudasset.assets.exportResource",
    "compute.commitments.list",
    "monitoring.timeSeries.list",
    "recommender.cloudsqlIdleInstanceRecommendations.get",
    "recommender.cloudsqlIdleInstanceRecommendations.list",
    "recommender.cloudsqlInstanceOutOfDiskRecommendations.get",
    "recommender.cloudsqlInstanceOutOfDiskRecommendations.list",
    "recommender.cloudsqlOverprovisionedInstanceRecommendations.get",
    "recommender.cloudsqlOverprovisionedInstanceRecommendations.list",
    "recommender.computeAddressIdleResourceInsights.get",
    "recommender.computeAddressIdleResourceInsights.list",
    "recommender.computeAddressIdleResourceRecommendations.get",
    "recommender.computeAddressIdleResourceRecommendations.list",
    "recommender.computeDiskIdleResourceInsights.get",
    "recommender.computeDiskIdleResourceInsights.list",
    "recommender.computeDiskIdleResourceRecommendations.get",
    "recommender.computeDiskIdleResourceRecommendations.list",
    "recommender.computeImageIdleResourceInsights.get",
    "recommender.computeImageIdleResourceInsights.list",
    "recommender.computeImageIdleResourceRecommendations.get",
    "recommender.computeImageIdleResourceRecommendations.list",
    "recommender.computeInstanceIdleResourceRecommendations.get",
    "recommender.computeInstanceIdleResourceRecommendations.list",
    "recommender.computeInstanceMachineTypeRecommendations.get",
    "recommender.computeInstanceMachineTypeRecommendations.list",
    "recommender.computeInstanceGroupManagerMachineTypeRecommendations.get",
    "recommender.computeInstanceGroupManagerMachineTypeRecommendations.list",
    "recommender.resourcemanagerProjectUtilizationRecommendations.get",
    "recommender.resourcemanagerProjectUtilizationRecommendations.list",
    "recommender.spendBasedCommitmentRecommendations.get",
    "recommender.spendBasedCommitmentRecommendations.list",
    "recommender.usageCommitmentRecommendations.get",
    "recommender.usageCommitmentRecommendations.list",
    "resourcemanager.folders.get",
    "resourcemanager.folders.list",
    "resourcemanager.organizations.get",
    "resourcemanager.projects.get",
    "resourcemanager.projects.list",
  ]
}
